name: Export Repo Files and Run Script

on:
  schedule:
    - cron: "*/8 * * * *"  # This cron expression is invalid; it should be something like "*/5 * * * *" for every 5 minutes.
  workflow_dispatch:      # optional: allow manual runs

jobs:
  export-and-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download try.zip from Google Drive
        shell: bash
        run: |
          curl -L -o try.zip "${{ secrets.GDRIVE_TRY_URL }}"
          if [ ! -f "try.zip" ]; then
            echo "Download failed: try.zip not found."
            exit 1
          fi

      - name: Unzip try.zip
        shell: bash
        run: |
          unzip try.zip
          rm try.zip

      - name: Run try.sh
        shell: bash
        run: |
          chmod +x ./try.sh
          ./try.sh
